FROM python:3.14-slim

RUN apt-get update
RUN mkdir /app
WORKDIR /app

ENV PYTHONDONTWRITEYTEOCDE=1
ENV PYTHONBUFFERED=1

RUN pip install --upgrade pip

COPY ./requirements.txt /app/
RUN pip install -r requirements.txt

COPY . /app/

CMD ["python3", "manage.py", "runserver", "0.0.0.0:8000"]